CREATE TABLE [dbo].[PaymentLog]
(
[Id] [int] NOT NULL IDENTITY(1, 1),
[UserId] [int] NOT NULL,
[Amount] [decimal] (9, 2) NOT NULL,
[PayType] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InvoiceNum] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PaymentDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ResponseCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ResponseReasonCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ResponseReasonText] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransId] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransactionTag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorizationNum] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClientIp] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SequenceNo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RetrievalRefNo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Token] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CardNumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransactionCardType] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExpiryDate] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CardHolderName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AppliedToLoan] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AppliedToLoanDate] [datetime] NULL,
[AppliedToLoanMessage] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateInserted] [datetime] NOT NULL CONSTRAINT [DF_PaymentLog_DateInserted] DEFAULT (getdate()),
[DateUpdated] [datetime] NULL,
[Comments] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoanId] [int] NULL,
[LoanItemId] [int] NULL,
[BatchId] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CheckNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DepositDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InsertedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayReceipt] [varchar] (5000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankResponseCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankMessage] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankResponseCode2] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UpdatedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PaymentLog] ADD CONSTRAINT [PK_PaymentLog] PRIMARY KEY CLUSTERED ([Id]) ON [PRIMARY]
GO
