CREATE TABLE [dbo].[AppFix_20200721]
(
[ApplicationID] [int] NOT NULL IDENTITY(1, 1),
[UserID] [int] NOT NULL,
[OfficerId] [int] NOT NULL,
[FirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleInitial] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressID] [int] NULL,
[ParentAddressID] [int] NULL,
[IsUSCitizen] [bit] NULL,
[IsMAResident] [bit] NULL,
[IsMMSStudent] [bit] NULL,
[MMSStudentID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HaveLoanCEF] [bit] NULL,
[MDDegreeFromSchool] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MDDegreeDate] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LocationAfterGrad] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsMarried] [bit] NULL,
[SpouseOccupation] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Children] [tinyint] NULL,
[ChildsAge] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsSpouseApplForLoan] [bit] NULL,
[Comments] [varchar] (5000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ApplicantSignature] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ApplicantSignedDate] [date] NULL,
[MMSLoanID] [tinyint] NOT NULL,
[LoanAmt] [decimal] (9, 2) NULL,
[OfficerSignature] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OfficerSignedDate] [date] NULL,
[MMSAmt] [decimal] (9, 2) NULL,
[MMSSignature] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MMSSignedDate] [date] NULL,
[ApplStatus] [int] NULL,
[LoanApprovedFlag] [bit] NULL,
[LoanApprovedDate] [date] NULL,
[Uniqueidentifier] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsDeleted] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateInserted] [datetime2] NULL,
[DateUpdated] [datetime2] NULL,
[InsertedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UpdatedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LockedForStudent] [bit] NULL,
[LockedForOfficer] [bit] NULL,
[LockedForAdmin] [bit] NULL,
[OfficerRejectComment] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MMSPrivateComment] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MMSLoanSignedDate] [date] NULL
) ON [PRIMARY]
GO
