CREATE TABLE [fn].[Invoices]
(
[InvoiceID] [int] NOT NULL IDENTITY(1, 1),
[InvoiceCurrentFlag] [int] NOT NULL,
[UserID] [int] NULL,
[Email] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleInitial] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Title] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InstitutionName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoanApprovedDate] [datetime] NOT NULL,
[Loan2ApprovedDate] [datetime] NULL,
[LoanLastPaymentDate] [datetime] NULL,
[StopLateFee] [decimal] (9, 2) NOT NULL,
[LoanAmt] [decimal] (9, 2) NULL,
[PayFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Comments] [varchar] (7000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ProjectedInterest] [numeric] (9, 2) NULL,
[PrincipalDue] [decimal] (9, 2) NOT NULL,
[PrincipalOverdue] [decimal] (9, 2) NOT NULL,
[InterestDue] [decimal] (9, 2) NOT NULL,
[InterestOverdue] [decimal] (9, 2) NOT NULL,
[Latefee] [decimal] (9, 2) NOT NULL,
[LateFeeInterest] [decimal] (9, 2) NOT NULL,
[ReturnedCheckFee] [decimal] (9, 2) NOT NULL,
[PrepaidPenalty] [decimal] (9, 2) NOT NULL,
[Balance] [decimal] (9, 2) NOT NULL,
[PrincipalPaidTotal] [decimal] (9, 2) NOT NULL,
[InterestPaidTotal] [decimal] (9, 2) NOT NULL,
[YearOfLoan] [int] NULL,
[FinancialChargesPaidTotal] [decimal] (9, 2) NOT NULL,
[TotalDue] [decimal] (9, 2) NULL,
[TotalOverDue] [decimal] (9, 2) NULL,
[EmailQueued] [datetime] NULL,
[DoNotSendInvoiceFlag] [bit] NULL CONSTRAINT [DF_Invoices_DoNotSendInvoice] DEFAULT ((0)),
[DateInserted] [datetime] NOT NULL CONSTRAINT [DF_Invoices_DateInserted] DEFAULT (getdate()),
[DateUpdated] [datetime] NULL CONSTRAINT [DF_Invoices_DateUpdated] DEFAULT (getdate()),
[IsDeleted] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_Invoices_IsDeleted] DEFAULT ('N'),
[InsertedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_Invoices_InsertedBy] DEFAULT (suser_sname()),
[UpdatedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_Invoices_UpdatedBy] DEFAULT (suser_sname()),
[Address1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalPrincipalDue] [decimal] (9, 2) NULL,
[TotalFees] [decimal] (9, 2) NULL,
[PayArrangementFlag] [bit] NULL,
[PayArrangementAmt] [decimal] (9, 2) NULL,
[DelayedPayStartDate] [date] NULL,
[PayArrangementComment] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [fn].[Invoices] ADD CONSTRAINT [PK_Invoices_1] PRIMARY KEY CLUSTERED ([InvoiceID], [InvoiceCurrentFlag]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_Invoices_UserID] ON [fn].[Invoices] ([UserID]) ON [PRIMARY]
GO
